services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - ./duplicates/backend:/app/backend
      - ./data/:/app/data
    command: >
       /bin/sh -c "python -m poetry run uvicorn backend.main:app --host 0.0.0.0 --port 8001 --reload"

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - ./duplicates/frontend/src:/app/src
      - ./duplicates/frontend/public:/app/public
    command: >
        /bin/sh -c "npm start"

  webserver:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/webserver/Dockerfile
    ports:
      - "80:80"

  triton:
    container_name: triton
    build:
      context: .
      dockerfile: docker/triton/Dockerfile
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]
    volumes:
      - ./duplicates/triton/models:/models
#    environment:
#      - NVIDIA_VISIBLE_DEVICES=all
    command: >
        /bin/sh -c "tritonserver --http-port=8002 --metrics-port=8003 --grpc-port=8004 --model-repository=/models"
    ports:
      - 8002:8002
      - 8003:8003
      - 8004:8004

  locust:
    container_name: locust
    image: locustio/locust
    ports:
      - 8089:8089
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --host http://backend:8001
    depends_on:
      - backend
